- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: yes

- name: Add Kubernetes GPG key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repo
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Install Kubernetes components
  apt:
    name: "{{ install_kubectl | ternary(['kubelet','kubeadm','kubectl'], ['kubelet','kubeadm']) }}"
    state: present
    update_cache: yes

- name: Hold packages
  command: apt-mark hold kubelet kubeadm