- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: yes

- name: Download Kubernetes GPG key
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key"
    dest: /tmp/kubernetes.key

- name: Convert GPG key
  command: >
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/ /"
    filename: kubernetes
    state: present

- name: Install Kubernetes components
  apt:
    name: "{{ install_kubectl | ternary(['kubelet','kubeadm','kubectl'], ['kubelet','kubeadm']) }}"
    state: present
    update_cache: yes

- name: Hold packages
  command: apt-mark hold kubelet kubeadm