[master]
controlplane ansible_host=127.0.0.1 ansible_ssh_private_key_file=~/vagrant/controlplane/.vagrant/machines/default/virtualbox/private_key

[worker]
node-1 ansible_host=127.0.0.1 ansible_ssh_private_key_file=~/vagrant/node-01/.vagrant/machines/default/virtualbox/private_key

[all:vars]
ansible_user=vagrant
ansible_port=2222